### ISSUE TITLE
[Bug]: [vue-runtime] TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by or2e** [DerYeger/vue-masonry-wall#43]
### Description

```
toRefs() expects a reactive object but received a plain one.
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
[Vue warn]: onBeforeUnmount is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
TypeError: Cannot read properties of null (reading 'isCE')
    at Object.renderSlot (/workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2937:34)
    at /workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@yeger/vue-masonry-wall/dist/masonry-wall.umd.js:13:1841
    at Object.renderList (/workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2874:22)
    at /workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@yeger/vue-masonry-wall/dist/masonry-wall.umd.js:13:1751
    at Object.renderList (/workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2874:22)
    at Proxy.<anonymous> (/workspaces/vodoley/vodoley-frontend/.output/server/node_modules/@yeger/vue-masonry-wall/dist/masonry-wall.umd.js:13:1395)
    at renderComponentRoot (file:///workspaces/vodoley/vodoley-frontend/.output/server/chunks/handlers/renderer.mjs:2961:45)
    at renderComponentSubTree (file:///workspaces/vodoley/vodoley-frontend/.output/server/chunks/handlers/renderer.mjs:10597:51)
    at renderComponentVNode (file:///workspaces/vodoley/vodoley-frontend/.output/server/chunks/handlers/renderer.mjs:10526:16)
    at Object.ssrRenderComponent (file:///workspaces/vodoley/vodoley-frontend/.output/server/chunks/handlers/renderer.mjs:10946:12)
```

### Reproduction

Nuxt project info:                                                                                                                                                  01:03:48
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Vue Version:     `3.2.37`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
------------------------------

The error is only thrown in the production build

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Interesting, the library works fine with Vite's SSR and SSG. This seems like a Nuxt 3/Vue Renderer bug, considering the stack trace.

**Comment by dosstx** [comment]
I wanted to say that I also just got this error when using it with nuxt 3 rc4 (not sure if the previous rc versions have the same issue).

**Comment by DerYeger** [comment]
This is an issue of Nuxt 3, see https://github.com/nuxt/framework/issues/2530.
Perhaps https://github.com/nuxt/framework/issues/2530#issuecomment-1110747586 can fix the problem.

**Comment by dosstx** [comment]
OK, I am not sure if I did this right, but I added this to my nuxt config:

```
    vite: {
        logLevel: 'info',
        optimizeDeps: {
            include: [
                '@yeger/vue-masonry-wall'
            ]
        }
    },
    ```
    
    Unfortunately, I still get the same error above. @or2e Can you let me know if you get this fixed and post the solution here?

**Comment by or2e** [comment]
@dosstx [dosstx](https://github.com/dosstx)

Studied the code of some Nuxt3 modules. Need to add:
https://v3.nuxtjs.org/guide/going-further/esm/#transpiling-libraries

**Comment by DerYeger** [comment]
> @dosstx [dosstx](https://github.com/dosstx)
> 
> Studied the code of some Nuxt3 modules. Need to add: https://v3.nuxtjs.org/guide/going-further/esm/#transpiling-libraries

Thank you very much for the workaround!
I added the required config changes to the README.

**Comment by DerYeger** [comment]
I just released v3.0.38 that should fix the issue without requiring the above workaround.
It also enables SSR support without defining a stub for the `ResizeObserver`.

**Comment by ManUtopiK** [comment]
I'm not sure this issue is correctly solved. I got the same error using "@yeger/vue-masonry-wall": "^3.0.42".
I use "nuxt": "3.0.0-rc.6" and node 16.15.1.

I added 
```js
 build: {
    transpile: ['@yeger/vue-masonry-wall'],
 }
```
to my `nuxt.config.ts` and it works well.

**Comment by DerYeger** [comment]
> I'm not sure this issue is correctly solved. I got the same error using "@yeger/vue-masonry-wall": "^3.0.42". I use "nuxt": "3.0.0-rc.6" and node 16.15.1.
> 
> I added
> 
> ```js
>  build: {
>     transpile: ['@yeger/vue-masonry-wall'],
>  }
> ```
> 
> to my `nuxt.config.ts` and it works well.

Looks like the migration to Vite 3 broke something. In the meantime, you could use 3.0.38. I gave that a try and it worked. See https://stackblitz.com/edit/github-enexbp?file=package.json,plugins%2Fvue-masonry-wall.ts,app.vue.

**Comment by DerYeger** [comment]
I narrowed it down to v3.0.40 of this library.
Since there's only one change, Nuxt 3 seems to be having issues with the valid `.mjs` extension.

**Comment by DerYeger** [comment]
Reported upstream at https://github.com/nuxt/framework/issues/6094

**Comment by DerYeger** [comment]
Will be closed by https://github.com/nuxt/framework/issues/4084.

**Comment by MogliCodes** [comment]
> I'm not sure this issue is correctly solved. I got the same error using "@yeger/vue-masonry-wall": "^3.0.42". I use "nuxt": "3.0.0-rc.6" and node 16.15.1.
> 
> I added
> 
> ```js
>  build: {
>     transpile: ['@yeger/vue-masonry-wall'],
>  }
> ```
> 
> to my `nuxt.config.ts` and it works well.

I had the same error using `nuxt 3.0.0-rc.6` and `v3.0.43` of this library. Adding 
```
build: {
        transpile: ['@yeger/vue-masonry-wall'],
    },
```
to `nuxt.config.ts` resolved the issue.

**Comment by danielroe** [comment]
We now add vue as an external by default. We can track any remaining issues in #4084.

**Comment by danielroe** [comment]
Sorry - originally posted thinking this was an issue in nuxt/framework - didn't mean to tell you to close it 😆
